name: multiple jobs
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world" 
        
  second_job:
    needs: first_job
    runs-on: ubuntu_latest
    steps:
      - name: print date
        run: date
    
