name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
      - qa

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run on Pull Request
        run: echo "Pull request raised"
