name: schedule 2min
on: 
  schedule:
    - cron: '*/2 * * * *' 
jobs:
  twomins-job:
     runs-on: ubuntu-latest 
     steps:
       - name: 5mins-job
         run: echo "running for every 5 mins"
 
    
