name: Scheduled Run

on: workflow_dispatch
 # schedule:
  #  - cron: '* * * * *' 

jobs:
  db-backup:
    runs-on: ubuntu-latest
    steps:
      - name: db backup
        run: echo "database backup is done"
